/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-3-27 上午8:13' with Gradle 3.2.1
 *
 * @author Administrator, @date 17-3-27 上午8:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
